server:
  port: 8080
  servlet:
    context-path: /cshop


#配置模板的后缀，自动读取spring.mvc.view.suffix
spring:
  mvc:
    view:
      suffix: .html
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

spring:
    datasource:
        name: cshop1
        url: jdbc:mysql://127.0.0.1:3306/cshop1
        username: root
        password: fadp
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20


mybatis:
  mapper-locations: classpath*:/com/whpu/*Mapper.xml

spring:
  application:
    name: mycat-jpa
  datasource:
    platform: mysql
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cshop2?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: fadp

