server:
  port: 8080
  servlet:
    context-path: /cshop


#配置模板的后缀，自动读取spring.mvc.view.suffix
spring:
  mvc:
    view:
      suffix: .html
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  datasource:
        name: cshopadmin
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/cshopadmin
        username: root
        password: fadp
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

  jpa:
      database: mysql
      show-sql: true
  aop:
    proxy-target-class: true


mybatis:
  mapper-locations: classpath*:/com/whpu.model/*Mapper.xml



spring:
  redis:
     shiro:
        host: 127.0.0.1
        port: 6379
        timeout: 0
        password: